apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: webapp-replicaset
        image: 937545311489.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
        env:
        - name: DBHOST
          value: "10.244.0.57"
        - name: DBPORT
          value: "3306"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
        - name: DBUSER
          value: "root"
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always