---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sqldb
  labels:
    app: mysql
    week: week5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
         image: 937545311489.dkr.ecr.us-east-1.amazonaws.com/mysql:v1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306
      dnsPolicy: ClusterFirst  
      restartPolicy: Always
        