---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp
  labels:
    app: employees
    week: week5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp-deployementc
        image: 937545311489.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
        env:
        - name: DBPWD
          value: "pw"
        ports:
        - containerPort: 80
        env:
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "10.244.0.16"
        - name: DBPORT
          value: "3306"
      dnsPolicy: ClusterFirst  
      restartPolicy: Always

