---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-pod-deployment
  namespace: sqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql-pod-container
        image: 937545311489.dkr.ecr.us-east-1.amazonaws.com/mysql:v1
        
