---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-pod-deployment
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp-pod-container
        image: 937545311489.dkr.ecr.us-east-1.amazonaws.com/webapp:v1