apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
spec:
  containers:
    - name: webapp-pod
      image: 937545311489.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
      ports:
        - containerPort: 80
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always