apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
spec:
  containers:
  - image: 937545311489.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
    name: webapp-pod-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
